# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#


############ Site settings

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Economics of Modern Power Systems"
subtitle: "ENVIRON 590.05 / ENERGY 590.05"
site.author: Luana Maranon Lima
email: "lmm89@duke.edu"
description: ""
baseurl: "/course-website" # the subpath of your site, e.g. /blog
url: "http://env590/env590.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lmmlima
repository: ENV590/env590.github.io

logo: "/docs/assets/logoNSOE.png"


############ Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
#remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag


# Outputting
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


exclude:
  - Gemfile
  - Gemfile.lock

include: ['_images', '_css','_data','_pages','_layout']


#github: [metadata]





#image: "/docs/assets/images/translines.jpeg"

#header:
#  teaser: /_images/nicholas-school-default.jpg



########### Site Author
author:
  name             : "Luana Lima"
  avatar           :  "/docs/assets/Luana_3-01.jpg"
  bio              : "Visiting Assistant Professor"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:lmm89@duke.edu"
    - label: "Sakai"
      icon: "fas fa-fw fa-link"
      # url: "https://sakai.duke.edu/portal/site/e91be29c-3e9b-41d7-830d-8cf20ef05c83/tool/db3d0124-5654-4b11-8451-1200db2bd344/main"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/lmmlima/"


# Site Footer
footer:
  links:
    - label: "Sakai"
      icon:
      url: "https://sakai.duke.edu/portal/site/fc198b90-9d77-4c6b-8708-c9d0d044be5b"
    - label: "Slack"
      icon: "fab fa-fw fa-slack"
      url: "https://app.slack.com/client/T03UBGNG030/C03U3HYP9PH"
#
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  # HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
#defaults:
##   # _docs
#   - scope:
#       path: "docs"
#       type: docs
#       layout: default
#       read_time: false
#       author_profile: true
#       share: false
#       comments: false
#       sidebar:
#         nav: "docs"
#   # _pages
#   - scope:
#       path: "_pages"
#       type: pages
#     values:
#       layout: default
#       sidebar:
#         nav: "modules"



# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
#
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-172014212-1"
#     anonymize_ip: false # default

#include: ['_images', '_css']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
